# Generated by Django 3.1.4 on 2020-12-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_title', models.CharField(max_length=25)),
                ('ebook_description', models.TextField()),
                ('ebook_preview_image', models.ImageField(upload_to='images/')),
                ('ebook_document', models.FileField(upload_to='books/')),
            ],
        ),
    ]
