# Generated by Django 3.1.4 on 2020-12-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0002_auto_20201208_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='ebook_description',
            field=models.TextField(max_length=750),
        ),
    ]
