# Generated by Django 3.1.4 on 2020-12-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0003_auto_20201208_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='ebook_title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
