# Generated by Django 3.1.4 on 2020-12-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
