# Generated by Django 3.1.4 on 2020-12-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0008_auto_20201214_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile/'),
        ),
    ]
