# Generated by Django 3.1.4 on 2020-12-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0010_ebook_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='likes',
        ),
    ]
