# Generated by Django 3.1.4 on 2020-12-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0018_ebook_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='author',
        ),
    ]
