# Generated by Django 3.1.4 on 2020-12-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0020_auto_20201219_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
