# Generated by Django 3.1.4 on 2020-12-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulebook', '0023_auto_20201219_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
